### PR TITLE
Get aliases from importlib.metadata

### PR DESCRIPTION
**Pull request by BeRT2me**
## Description

`importlib.metadata` has `packages_distributions` which "Returns a mapping of top-level packages to their distributions." This is essentially what `poly check` needs on a silver platter!

Because Plugins don't run in the same environment, this leverages Poetry's `EnvManager` to get the proper environment's package to distribution mapping. Closely mirroring [packages_distributions](https://github.com/python/cpython/blob/97ce15c5f8743fb8b8967c6a05d6aec9fef9cbc7/Lib/importlib/metadata/__init__.py#L1043) from `importlib.metadata`, except keys/values are swapped to fit with existing code.

Using this, as long as the commands aren't being run in vacuum, fuzzy matching may not even be necessary~

## Motivation and Context

I feel this more robustly solves https://github.com/DavidVujic/python-polylith/issues/107 

## How Has This Been Tested?

- Add and install `opencv-python-headless` using poetry.
- Add `import cv2` in the project. 
  - Run `poetry poly check -C <path>` 
    - No issues!
  - Remove `opencv-python-headless` and re-lock.
  - Run `poetry poly check -C <path>` 
    - Yes issues!

I also tested in various environments with `--strict` and a `cutoff` of `1.0` rather than just `0.9` to fully bypass `filter_close_matches`, with 0 issues~

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have read the [code of conduct](https://github.com/davidvujic/python-polylith/blob/master/CODE-OF-CONDUCT.md).
- [x] I have read the [contributing guide](https://github.com/davidvujic/python-polylith/blob/master/CONTRIBUTING.md).
- [ ] I have updated the documentation accordingly (if applicable).

### CODE REVIEW

**Comment by DavidVujic** [comment]
Thank you for making a Pull Request to this project! ⭐ 

I will have a look during this week!

**Comment by DavidVujic** [comment]
This is a huge improvement 🚀  

I will merge this in to the main branch and publish a new version to PyPI shortly. While experimenting with the things I have learned from your PR, I wanted to give it a try to do something in a "functional programming-ish" way that has been a guideline for me during the work with the poly tool.

Here's what I came up with during learning and trying this out:

```python
def top_level_packages(dist) -> List[str]:
    top_level = dist.read_text("top_level.txt")

    return str.split(top_level or "")


def mapped_packages(dist) -> dict:
    packages = top_level_packages(dist)
    name = dist.metadata["name"]

    return {name: package for package in packages}


def packages_distributions(dists) -> dict[str, List[str]]:
    """Return a mapping of top-level packages to their distributions."""
    return reduce(lambda acc, dist: {**acc, **mapped_packages(dist)}, dists, {})
```

```python
def distributions(poetry: Poetry, path: Union[Path, None]):
    project_poetry = Factory().create_poetry(path) if path else poetry
    env = EnvManager(project_poetry).get()
    
    return env.site_packages.distributions()
```

**Comment by BeRT2me** [comment]
Your more "functional programming-ish" way looks great to me! 

One thought I had after the fact, I probably should have renamed `packages_distributions` to `distributions_packages`, (and `pkg_to_dist` to `dist_to_pkg`) since what is produced is better described by 
> """Return a mapping of distributions to their top-level packages.""" 

Oops🙃

**Comment by DavidVujic** [comment]
> Your more "functional programming-ish" way looks great to me!
> 
> One thought I had after the fact, I probably should have renamed `packages_distributions` to `distributions_packages`, (and `pkg_to_dist` to `dist_to_pkg`) since what is produced is better described by
> 
> > """Return a mapping of distribution names to their top-level packages."""
> 
> Oops🙃

I have a Pull Request that continues the work from this one, and also renamed the function to `distribution_packages`. 😄

**Pull request merged**
